# Generated by Django 3.2.9 on 2021-12-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktweetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_recommemdation', models.CharField(max_length=5000)),
                ('pub_date', models.CharField(max_length=100)),
            ],
        ),
    ]
